### ISSUE TITLE
System.InvalidOperationException: A second operation started on this context before a previous operation completed.

### ISSUE THREAD

**Issue by max-favilli** [serilog/serilog-aspnetcore#125]
I am setting up Serilog in program.cs as follow:

    public static void Main(string[] args)
    {
      Log.Logger = new LoggerConfiguration()
          .ReadFrom.Configuration(Configuration)
          .Enrich.FromLogContext()
          .CreateLogger();

In startup.cs I have added this middleware:
```
 app.UseMiddleware<umusa.SerilogMiddleware>();
```

My appsettings configuration:
```
  "Serilog": {
    "MinimumLevel": {
      "Default": "Warning",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "MSSqlServer",
        "Args": {
          "connectionString": "---my-connection-string---",
          "tableName": "aahLogs",
          "autoCreateSqlTable": true,
          "columnOptionsSection": {
            "addStandardColumns": [ "LogEvent" ]
          },
          "customColumns": [
            {
              "ColumnName": "errorIdForUser",
              "DataType": "uniqueidentifier",
              "AllowNull": true
            }
          ]
        }
      }
    ]
  }

```
In my middleware:
```
    public async Task Invoke(HttpContext httpContext, IHostingEnvironment _env, IConfiguration _configuration)
    {
      if (httpContext == null) throw new ArgumentNullException(nameof(httpContext));

      var sw = Stopwatch.StartNew();
      if (_env.IsDevelopment())
      {
        try
        {
          await _next(httpContext);
          sw.Stop();

          var statusCode = httpContext.Response?.StatusCode;
          //var level = statusCode > 499 ? LogEventLevel.Error : LogEventLevel.Information;
          var level = statusCode > 399 ? LogEventLevel.Error : LogEventLevel.Information;

          var log = level == LogEventLevel.Error ? LogForErrorContext(httpContext, _env, null, null, null) : Log;
          log.Write(level, MessageTemplate, httpContext.Request.Method, httpContext.Request.Path, httpContext.Request.QueryString, statusCode, sw.Elapsed.TotalMilliseconds);
        }
        // Never caught, because `LogException()` returns false.
        catch (Exception ex) when (LogException(httpContext, _env, sw, ex, _configuration)) { }
      }
      else
      {
        try
        {
          await _next(httpContext);
          sw.Stop();

          var statusCode = httpContext.Response?.StatusCode;
          //var level = statusCode > 499 ? LogEventLevel.Error : LogEventLevel.Information;
          var level = statusCode > 399 ? LogEventLevel.Error : LogEventLevel.Information;

          var log = level == LogEventLevel.Error ? LogForErrorContext(httpContext, _env) : Log;
          log.Write(level, MessageTemplate, httpContext.Request.Method, httpContext.Request.Path, httpContext.Request.QueryString, statusCode, sw.Elapsed.TotalMilliseconds);
        }
        // Never caught, because `LogException()` returns false.
        catch (Exception ex)
        {
          LogException(httpContext, _env, sw, ex, _configuration);
          return;
        }
      }
    }
```

On every exception being logged I am getting and additional exception:

```
System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext, however instance members are not guaranteed to be thread safe. This could also be caused by a nested query being evaluated on the client, if this is the case rewrite the query avoiding nested invocations.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at umusa.ConfigurationUtility..ctor(IMemoryCache memoryCache, gommeautoContext context, HttpContext httpContext, IHostingEnvironment hostingEnvironment, ClaimsPrincipal user, IConfiguration Configuration) in C:\websites-repo\gommecore\umusa\ConfigurationUtility.cs:line 43
   at maduka.Controllers.WheelsController.Index(String cerchi, String chunka, String chunkb, String chunkc, Nullable`1 carid, Nullable`1 diameter, String chassis, String type, String diameters, String wheelbrand, String wheelmodel, String wheelholes, String wheelcolor) in C:\websites-repo\gommecore\maduka\Controllers\WheelsController.cs:line 881
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at umusa.SerilogMiddleware.Invoke(HttpContext httpContext, IHostingEnvironment _env, IConfiguration _configuration) in C:\websites-repo\gommecore\umusa\Serilog\CustomEnricher.cs:line 60
```
I am using netcore 2.2.6 and EF Core.

**What am I doing wrong?**

**Comment by max-favilli** [comment]
After hours of investigation **we found out this problem had nothing to do with serilog**. 
In case anyone with a similar problem ends up here.

We had an async method call not awaited in our code, in a base controller shared by all of our mvc controllers. Apparently it started triggering this exception after upgrading to netcore 2.2.6
