### ISSUE TITLE
UseSerilog with configuration delegate throws exception

### ISSUE THREAD

**Issue by ip75** [serilog/serilog-aspnetcore#205]
The Serilog maintainers want you to have a great experience using Serilog, and will happily track down and resolve bugs. We all have limited time, though, so please think through all of the factors that might be involved and include as much useful information as possible 😊.

ℹ If the problem is caused by a sink or other related package, please try to track down the correct repository for that package and create the report there: this tracker is for the  **Serilog.AspNetCore** package only.

**Description**
exception

**Reproduction**
appsettings.json has section "Serilog"

                        .UseSerilog((hostingContext, loggerConfiguration) => loggerConfiguration
                            .ReadFrom.Configuration(hostingContext.Configuration, "Serilog")
                            .Enrich.FromLogContext()
                            .WriteTo.Elasticsearch(
                                new ElasticsearchSinkOptions(new Uri("http://elk:9200"))
                                {
                                    AutoRegisterTemplate = true,
                                    AutoRegisterTemplateVersion = AutoRegisterTemplateVersion.ESv7
                                })

```
address_1           | Unhandled exception. System.InvalidCastException: **Invalid cast from 'System.String' to 'System.IFormatProvider'.**
address_1           |    at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
address_1           |    at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
address_1           |    at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
address_1           |    at System.Convert.ChangeType(Object value, Type conversionType)
address_1           |    at Serilog.Settings.Configuration.StringArgumentValue.ConvertTo(Type toType, ResolutionContext resolutionContext)
address_1           |    at Serilog.Settings.Configuration.ConfigurationReader.<>c__DisplayClass18_2.<CallConfigurationMethods>b__3(<>f__AnonymousType9`2 <>h__TransparentIdentifier0)
address_1           |    at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
address_1           |    at System.Linq.Enumerable.SelectListPartitionIterator`2.ToList()
address_1           |    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
address_1           |    at Serilog.Settings.Configuration.ConfigurationReader.CallConfigurationMethods(ILookup`2 methods, IList`1 configurationMethods, Object receiver)
address_1           |    at Serilog.Settings.Configuration.ConfigurationReader.ApplySinks(LoggerConfiguration loggerConfiguration)
address_1           |    at Serilog.Settings.Configuration.ConfigurationReader.Configure(LoggerConfiguration loggerConfiguration)
address_1           |    at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
address_1           |    at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, String sectionName, DependencyContext dependencyContext)
address_1           |    at Address.API.Program.<>c.<CreateHostBuilder>b__1_5(WebHostBuilderContext hostingContext, LoggerConfiguration loggerConfiguration) in /Address.API/src/Services/Address/Address.API/Program.cs:line 50
address_1           |    at Serilog.SerilogWebHostBuilderExtensions.<>c__DisplayClass1_0.<UseSerilog>b__0(WebHostBuilderContext context, IServiceCollection collection)
address_1           |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass10_0.<ConfigureServices>b__0(HostBuilderContext context, IServiceCollection builder)
address_1           |    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
address_1           |    at Microsoft.Extensions.Hosting.HostBuilder.Build()
address_1           |    at Address.API.Program.Main(String[] args) in /Address.API/src/Services/Address/Address.API/Program.cs:line 17
address_1           |    at Address.API.Program.<Main>(String[] args)

```
**Expected behavior**
configuration passed with no exceptions

**Relevant package, tooling and runtime versions**
Serilog.AspNetCore 3.4.0 on Windows 10 in docker ubuntu:latest

**Additional context**

**Comment by ip75** [comment]
wrong values in appsettings.json Serilog section. "Name": "Elasticsearch"
guys update your documentation when you change code.
https://github.com/serilog/serilog-sinks-elasticsearch  your example here follows the exception mentioned above.

**Comment by nblumhardt** [comment]
PRs to the docs are welcome.
