### ISSUE TITLE
Log.CloseAndFlush() breaks add-migration

### ISSUE THREAD

**Issue by domagojmedo** [serilog/serilog-aspnetcore#276]
**Description**
If you are logging startup code in .NET 6 and you have try-catch with Log.CloseAndFlush() then invoking ef commands results in them not writing to console.

**Reproduction**
https://github.com/domagojmedo/WebApplication4

In this app if you call update-database you get normal EF output in package manager console. But if you uncomment Log.CloseAndFlush() call then you don't get the rest of the message.

Without:
```
Build started...
Build succeeded.
[14:53:22 INF] Starting up
[14:53:22 INF] Exception
Microsoft.Extensions.Hosting.HostFactoryResolver+HostingListener+StopTheHostException: Exception of type 'Microsoft.Extensions.Hosting.HostFactoryResolver+HostingListener+StopTheHostException' was thrown.
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in C:\Users\DomagojMedo\source\repos\WebApplication4\WebApplication4\Program.cs:line 18
[14:53:22 INF] Shut down complete
[14:53:22 INF] Entity Framework Core 6.0.0 initialized 'TestContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer:6.0.0' with options: None
[14:53:22 INF] Executed DbCommand (11ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
[14:53:22 INF] Executed DbCommand (9ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
[14:53:22 INF] Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
[14:53:22 INF] Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
[14:53:22 INF] Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
[14:53:22 INF] No migrations were applied. The database is already up to date.
Done.
```

With:

```
Build started...
Build succeeded.
[14:53:57 INF] Starting up
[14:53:57 INF] Exception
Microsoft.Extensions.Hosting.HostFactoryResolver+HostingListener+StopTheHostException: Exception of type 'Microsoft.Extensions.Hosting.HostFactoryResolver+HostingListener+StopTheHostException' was thrown.
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in C:\Users\DomagojMedo\source\repos\WebApplication4\WebApplication4\Program.cs:line 18
[14:53:57 INF] Shut down complete
Done.
```

**Expected behavior**
EF migration message should be displayed in the PMC

Not sure if this is problem with Serilog of EF Core

**Comment by skomis-mm** [comment]
Hi @domagojmedo ,
Hmm, seems this is [how it works](https://andrewlock.net/exploring-dotnet-6-part-5-supporting-ef-core-tools-with-webapplicationbuilder/#updates-to-the-hostfactoryresolver) in order to support top-level statements, keeping you in the state of constant amazement :D. 

The whole method is executed by EF tool. Simple workaround would be something like whis:
```csharp
if (new StackTrace().FrameCount == 1) 
{
    Log.CloseAndFlush();
}
```

**Comment by domagojmedo** [comment]
I did it with 
```
 if (!isDevelopmentEnvironment)
 {
     Log.CloseAndFlush();
 }
```

But both options are kinda meh IMHO. Wish there was a better way

**Comment by nblumhardt** [comment]
Wow, that's a deeply troubling bit of tooling; guess they couldn't have had many options, given the introduction of top-level statements 😅
