### ISSUE TITLE
Cannot apply JsonCompactFormatter to ConsoleSink

### ISSUE THREAD

**Issue by zippy1981** [serilog/serilog-aspnetcore#48]
This is similar to #31, except I am not attempting to comingle `ITextFormatter` and the an Output template. Also its for the Console sink not the Rolling Log Sink

**Program.cs**
```
            WebHost.CreateDefaultBuilder(args)
                .UseApplicationInsights()
                .UseStartup<Startup>()
                .UseSerilog()  // Exception thrown here
                .Build();

```

**Startup.cs:**
```
            Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(Configuration)
                .Destructure.ByTransforming<CultureInfo>(c => new { c.LCID, c.Name })
                .Destructure.ByTransforming<Claim>(c => new { c.Subject, c.Type, c.Value, c.ValueType, c.Issuer, c.OriginalIssuer })
                .Destructure.ByTransforming<LocalDate>(date => date.ToDateTimeUnspecified())
                .CreateLogger();
```

**appsettings.json:**
```
  "Serilog": {
    "Using": [ "Serilog.Sinks.Console" ],
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "MediatR.IMediator": "Information", 
        "Microsoft": "Information",
        "Microsoft.AspNetCore.Mvc": "Verbose",
        "Microsoft.EntityFrameworkCore": "Warning",
        "Foo.Authentication": "Info"
      }
    },
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact",
          //"theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console"
          // "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {RequestId}-{SourceContext} {Scope}: {Message:lj}{NewLine}{Exception}"
        },
        "restrictedToMinimumLevel":  "Information" 
      },
      {
        "Name": "ApplicationInsightsTraces",
        "Args": { "instrumentationKey": "fbe3b6f4-74d2-4afb-b068-718255943a34" } 
      }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId", "WithExceptionDetails" ],
    "Properties": {
      "Application": "Foo"
    }
  },
```

**Exception:**
```
System.InvalidCastException: Invalid cast from 'System.String' to 'Serilog.Formatting.ITextFormatter'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at Serilog.Settings.Configuration.StringArgumentValue.ConvertTo(Type toType, IReadOnlyDictionary`2 declaredLevelSwitches)
   at Serilog.Settings.Configuration.ConfigurationReader.<>c__DisplayClass17_3.<CallConfigurationMethods>b__4(<>f__AnonymousType6`2 <>h__TransparentIdentifier0)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListPartitionIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Serilog.Settings.Configuration.ConfigurationReader.CallConfigurationMethods(ILookup`2 methods, IList`1 configurationMethods, Object receiver, IReadOnlyDictionary`2 declaredLevelSwitches)
   at Serilog.Settings.Configuration.ConfigurationReader.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at Foo.Startup.ConfigureServices(IServiceCollection services) in C:\Users\justin.dearing\source\repos\foo\Foo\Startup.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Vsu.Cyber.Server.Program.BuildWebHost(String[] args) in C:\Users\justin.dearing\source\repos\foo\Foo\Program.cs:line 16
   at Vsu.Cyber.Server.Program.Main(String[] args) in C:\Users\justin.dearing\source\repos\vsu-cyber-server\Vsu.Cyber.Server\Program.cs:line 12
```

I can use the output formatter and the color theme just fine.

**Comment by nblumhardt** [comment]
Hi! One quick observation: `"restrictedToMinimumLevel":  "Information"` needs to go inside the `"Args"` block.

The most likely cause I can spot here is the _Serilog.Formatting.Compact.dll_ assembly not being available to the app - is it being copied to the output dir?
